@startuml
left to right direction

actor Usuario

usecase "Iniciar\nsesión" as UC1
usecase "Usar\naplicación" as UC2
usecase "Gestionar\ncuenta" as UC3

usecase "Visualizar\ndatos" as UC4
usecase "Gestionar\nfavoritos" as UC5
usecase "Consultar análisis\navanzados" as UC6
usecase "Usar\nchatbot" as UC7
usecase "Simular\ntemporada" as UC8

usecase "Crear\ncuenta" as UC9
usecase "Ver\nperfil" as UC10
usecase "Modificar\nperfil" as UC11
usecase "Cambiar\ncontraseña" as UC12
usecase "Eliminar\ncuenta" as UC13
usecase "Cerrar\nsesión" as UC14

Usuario --> UC1
Usuario --> UC2
Usuario --> UC3
Usuario --> UC14

UC2 --> UC4
UC2 --> UC5
UC2 --> UC6
UC2 --> UC7
UC2 --> UC8

UC3 --> UC9
UC3 --> UC10
UC3 --> UC11
UC3 --> UC12
UC3 --> UC13

@enduml